# Generated by Django 4.2.3 on 2023-07-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='roles',
            field=models.CharField(choices=[('user', 'Simple User'), ('admin', 'Admin User')], default='user', max_length=10),
        ),
    ]
